name: Close Review Labeler

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  contents: read

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/waiting-for-review-labeler@main
        with:
          hours-before-add-label: 0
          label-name: merged
